name: Generar Resumen de Noticias

on:
  schedule:
    - cron: '0 7 * * *'  # Reporte diario
    - cron: '0 8 * * 0'  # Reporte semanal los Domingos
  
  workflow_dispatch:
    inputs:
      report_type:
        description: 'Tipo de reporte a generar manualmente'
        required: true
        default: 'diario'
        type: choice
        options:
        - diario
        - semanal

jobs:
  generate_and_deploy_reports:
    name: Generar y Desplegar Reportes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Cache del historial de noticias
      # ... (sin cambios)
      id: cache-historial
      uses: actions/cache@v4
      with:
        path: historial_noticias.json
        key: ${{ runner.os }}-historial-noticias

    - name: Configurar Python e Instalar dependencias
      # ... (sin cambios)
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Ejecutar script de noticias
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        GMAIL_USER: ${{ secrets.GMAIL_USER }}
        GMAIL_DESTINATARIO: ${{ secrets.GMAIL_DESTINATARIO || secrets.GMAIL_USER }}
        BASE_WEB_URL: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
        GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      run: |
        # Lógica para decidir qué comando ejecutar
        if [[ "${{ github.event_name }}" == "schedule" && "${{ github.event.schedule }}" == "0 8 * * 0" ]]; then
          echo "Ejecutando reporte semanal (agendado)..."
          python compila_noticias.py --weekly
        elif [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.event.inputs.report_type }}" == "semanal" ]]; then
          echo "Ejecutando reporte semanal (manual)..."
          python compila_noticias.py --weekly
        else
          echo "Ejecutando reporte diario (agendado o manual por defecto)..."
          python compila_noticias.py
        fi

    - name: Desplegar reportes a GitHub Pages
      # ... (sin cambios)
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy news summary to GitHub Pages'