name: Generar Resumen de Noticias

on:
  schedule:
    - cron: '0 7 * * *'  # Reporte diario
    - cron: '0 8 * * 0'  # Reporte semanal los Domingos
  
  workflow_dispatch:
    inputs:
      report_type:
        description: 'Tipo de reporte a generar manualmente'
        required: true
        default: 'diario'
        type: choice
        options:
        - diario
        - semanal

jobs:
  generate_and_deploy_reports:
    name: Generar y Desplegar Reportes
    runs-on: ubuntu-latest
    env:
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
      GMAIL_USER: ${{ secrets.GMAIL_USER }}
      GMAIL_DESTINATARIO: ${{ secrets.GMAIL_DESTINATARIO || secrets.GMAIL_USER }}
      BASE_WEB_URL: "https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/"
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4

    - name: Cache del historial de noticias
      id: cache-historial
      uses: actions/cache@v4
      with:
        path: historial_noticias.json
        key: ${{ runner.os }}-historial-noticias

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Ejecutar Reporte Diario
      if: (github.event_name == 'schedule' && github.event.schedule == '0 7 * * *') || (github.event_name == 'workflow_dispatch' && github.event.inputs.report_type == 'diario')
      run: |
        echo "Ejecutando reporte diario..."
        python compila_noticias.py

    - name: Ejecutar Reporte Semanal
      if: (github.event_name == 'schedule' && github.event.schedule == '0 8 * * 0') || (github.event_name == 'workflow_dispatch' && github.event.inputs.report_type == 'semanal')
      run: |
        echo "Ejecutando reporte semanal..."
        python compila_noticias.py --weekly

    - name: Desplegar reportes a GitHub Pages
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Deploy news summary to GitHub Pages'
        keep_files: true